'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GPO_USLM_Tools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html&quot;&gt;
        '''&lt;title&gt;GPO OUTPUT XML Report&lt;/title&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''
        '''body {
        '''font-family: sans-serif,arial;
        '''color: #000000
        '''}
        '''
        '''p {
        '''font-size: 60%;
        '''}
        '''
        '''.tbl {
        '''border-collapse: collapse;
        '''margin: 25px 0;
        '''font-size: 0.9em;
        '''font-family: sans-serif;
        '''width: 100%;
        '''box-shadow: 0 0 20px rgba(0, 0, 0, 0.15)
        '''}
        '''
        '''.tbl thead tr {
        '''background-color: #009879;
        '''color: #ffffff;
        '''text-align: left;
        '''}
        '''
        '''.tbl th,
        '''.tbl td {
        '''padding: 12px 15px;
        '''te [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Report_Template() As String
            Get
                Return ResourceManager.GetString("Report_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;?xml-stylesheet type=&quot;text/css&quot; href=&quot;uslm.css&quot;?&gt;
        '''&lt;statutesAtLarge xmlns=&quot;http://schemas.gpo.gov/xml/uslm&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xml:lang=&quot;en&quot; xsi:schemaLocation=&quot;http://schemas.gpo.gov/xml/uslm https://www.govinfo.gov/schemas/xml/uslm/uslm-2.0.10.xsd&quot;&gt;
        '''&lt;meta&gt;
        '''&lt;dc:publisher&gt;United States Government Publishing Office&lt;/dc:publisher&gt;
        '''&lt;dc:format&gt;text/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Viewer_Template() As String
            Get
                Return ResourceManager.GetString("Viewer_Template", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
